export const PLANS = [
  {
    id: "free",
    name: "Free",
    slug: null, // No Polar product
    price: "$0",
    priceMonthly: 0,
    priceYearly: 0,
    description: "Perfect for getting started.",
    features: [
      "1 case study per month",
      "10 min max interview length",
      "5 MB storage",
      "AI narrative extraction",
      "Basic writing tone",
      "1 team seat",
      "Email support (48h)",
    ],
    limits: {
      caseStudies: 1,
      videoLength: 10, // minutes
      storage: 5, // MB
      socialPosts: 0,
      teamSeats: 1,
      designTemplates: 1,
    },
    cta: "Current Plan",
    popular: false,
  },
  {
    id: "freelancer",
    name: "Freelancer",
    slug: "starter",
    price: "$29",
    priceMonthly: 29,
    priceYearly: 290,
    description: "Built for independent professionals.",
    features: [
      "5 case studies per month",
      "30 min max interview length",
      "50 MB storage",
      "AI narrative extraction",
      "1 social post per case study",
      "Advanced writing tone",
      "No Casevia branding",
      "3 design templates",
      "1 team seat",
      "Email support (24h)",
    ],
    limits: {
      caseStudies: 5,
      videoLength: 30,
      storage: 50,
      socialPosts: 1,
      teamSeats: 1,
      designTemplates: 3,
    },
    cta: "Upgrade to Freelancer",
    popular: false,
  },
  {
    id: "pro",
    name: "Pro",
    slug: "pro",
    price: "$79",
    priceMonthly: 79,
    priceYearly: 790,
    description: "For growing teams handling more volume.",
    features: [
      "20 case studies per month",
      "60 min max interview length",
      "2 GB storage",
      "AI narrative extraction",
      "3 social posts per case study",
      "SEO title & slug suggestions",
      "Full tone + persona customization",
      "No Casevia branding",
      "10 design templates",
      "5 team seats",
      "Analytics dashboard",
      "Priority support (4h)",
    ],
    limits: {
      caseStudies: 20,
      videoLength: 60,
      storage: 2048,
      socialPosts: 3,
      teamSeats: 5,
      designTemplates: 10,
    },
    cta: "Upgrade to Pro",
    popular: true,
  },
  {
    id: "agency",
    name: "Agency",
    slug: "agency",
    price: "$149",
    priceMonthly: 149,
    priceYearly: 1490,
    description: "For agencies and larger content teams.",
    features: [
      "50 case studies per month",
      "120 min max interview length",
      "5 GB storage",
      "AI narrative extraction",
      "Unlimited social posts",
      "SEO title & slug suggestions",
      "Full tone + persona customization",
      "No Casevia branding",
      "10 design templates",
      "Unlimited team seats",
      "Analytics dashboard",
      "High-priority processing",
      "Dedicated account manager",
    ],
    limits: {
      caseStudies: 50,
      videoLength: 120,
      storage: 5120,
      socialPosts: -1,
      teamSeats: -1,
      designTemplates: 10,
    },
    cta: "Contact Sales",
    popular: false,
  },
] as const;

export type PlanId = (typeof PLANS)[number]["id"];
export type Plan = (typeof PLANS)[number];
