export const PLANS = [
  {
    id: "starter",
    name: "Starter",
    slug: null,
    price: "$0",
    priceMonthly: 0,
    priceYearly: 0,
    description: "Perfect for trying Casevia on one customer story.",
    badge: "Free forever",
    features: [
      "1 case study per month",
      "10 min max interview length",
      "250 MB storage",
      "AI narrative extraction",
      "Basic brand tone",
      "Casevia watermark on exports",
      "Single-user workspace",
      "Email support (48h)",
    ],
    limits: {
      caseStudies: 1,
      videoLength: 10,
      storage: 250,
      socialPosts: 0,
      teamSeats: 1,
      designTemplates: 1,
      branding: "watermark",
      customTone: false,
      analytics: false,
      prioritySupport: false,
      whiteLabel: false,
    },
    cta: "Get started free",
    popular: false,
  },

  {
    id: "freelancer",
    name: "Freelancer",
    slug: "starter",
    price: "$29",
    priceMonthly: 29,
    priceYearly: 290,
    description: "For solo operators and creators working with clients.",
    features: [
      "8 case studies per month",
      "30 min max interview length",
      "2 GB storage",
      "2 social posts per case study",
      "Tone customization",
      "No watermark",
      "5 design templates",
      "2 team seats",
      "Email support (24h)",
    ],
    limits: {
      caseStudies: 8,
      videoLength: 30,
      storage: 2048,
      socialPosts: 2,
      teamSeats: 2,
      designTemplates: 5,
      branding: "none",
      customTone: true,
      analytics: false,
      prioritySupport: false,
      whiteLabel: false,
    },
    cta: "Upgrade to Freelancer",
    popular: false,
  },

  {
    id: "pro",
    name: "Pro",
    slug: "pro",
    price: "$79",
    priceMonthly: 79,
    priceYearly: 790,
    description: "For growing teams producing stories on repeat.",
    popular: true,
    badge: "Most Popular",
    features: [
      "25 case studies per month",
      "60 min max interview length",
      "5 GB storage",
      "5 social posts per case study",
      "SEO title & metadata suggestions",
      "Advanced tone + persona control",
      "No Casevia branding",
      "20 design templates",
      "5 team seats",
      "Analytics dashboard",
      "Priority support (4h SLA)",
    ],
    limits: {
      caseStudies: 25,
      videoLength: 60,
      storage: 5120,
      socialPosts: 5,
      teamSeats: 5,
      designTemplates: 20,
      branding: "none",
      customTone: true,
      analytics: true,
      prioritySupport: true,
      whiteLabel: false,
    },
    cta: "Upgrade to Pro",
  },

  {
    id: "agency",
    name: "Agency",
    slug: "agency",
    price: "$199",
    priceMonthly: 199,
    priceYearly: 1990,
    description: "For agencies delivering stories at scale.",
    features: [
      "40 case studies per month",
      "120 min max interview length",
      "10 GB storage",
      "Unlimited social posts",
      "Full SEO optimization",
      "Brand voice + structure training",
      "White-label exports & portal",
      "30 design templates",
      "Unlimited team seats",
      "Advanced analytics + reporting",
      "High-priority processing",
      "Dedicated account manager",
    ],
    limits: {
      caseStudies: 40,
      videoLength: 120,
      storage: 10240,
      socialPosts: -1,
      teamSeats: -1,
      designTemplates: 30,
      branding: "white-label",
      customTone: true,
      analytics: true,
      prioritySupport: true,
      whiteLabel: true,
    },
    cta: "Talk to sales",
    popular: false,
  },
] as const;

export type PlanId = (typeof PLANS)[number]["id"];
export type Plan = (typeof PLANS)[number];
